# Use the official NGINX base image
FROM nginx:latest

# Copy your NGINX configuration file from the host into the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the SSL certificate and key to the container
COPY server.crt /app/server.crt
COPY server.key /app/server.key

COPY server.crt /etc/nginx/server.crt
COPY server.key /etc/nginx/server.key

# Expose port 443 for HTTPS traffic
EXPOSE 443
